inwx_credentials: ENC[AES256_GCM,data:Sgg1+UFMT2Ghy6yBhmN5jt4kBCP9uW+XfFJVja011oQJGBnRahdO8TfH23yi055pdZP4F/FjTUxWvEijg5PqhVoZBbC0eVnklNfRfwjCI5KZVqtZAC538rrdYv/LYlsTqQdlul7cqa+m7UEPtLgAiI/6ee0C2nUYk/n8jRzLSgVEG0FsC/MV+t9aUQ==,iv:2Pbt282cWV8tlommQU7ZT7U4SDqeMITB2u69vuhmtbY=,tag:pCY5i/agwpwn2yA4D4cjRA==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a2dHaEI2a2lYWDNaU2tI
            R1JGZzNmZW9hVDhSQXJtc1ZsVWFUeWoxMGkwCnp2R1RicVpsSVdnU3YzMFNzYytI
            MFZWNjNzSWxWdytCbStkSzhkUm5ib0EKLS0tIHZNZ09IVkNIczZ3WVJNMDFWd2ds
            cE1obmRQeEdtZGxLd1pIU0s5bmxGNFkKpGgA+tXgDpDkGNY9OlzYEDts+EItF5XM
            yPv4XB78SIuUFjcBw9k5vO7aKjZROgHkqK21Dgs7yO2ETGNMue0lsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T17:21:54Z"
    mac: ENC[AES256_GCM,data:zKXgTofTeVUy9ojKctH5xXKSRl/2lzZTKL947mnbkNLy/4MW/Goqr6Mi5vExv2QG9pkkCwsq3kppsNBZAq7gpoWV2S4dDziUdG+Z7psbyXLdMpjjzk1DFRr77BVT/DdE01BrULb1sqLdFzbMkJDSn3lDirmfMVVV3a9s3GAn/dY=,iv:CqHa+j63U9rr3SDDiQr5+qWRoNom73dell8wQ6i3Xxo=,tag:K2KeB4gWx9Qg0kvU+duftg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
