inwx_credentials: ENC[AES256_GCM,data:0PFT59xGSsaxXZU7pXy3QF8Zn4GIlsZ3vBGzDz+ve6ViJBdRzaSmr6DvGH6YnGOksL3mPWDKJ/NQ5gKFdJ7uIPVjPHUpbqmnkX40IX/dE762Mop1mefXq/MANEBI8eoTigSJSpFEWVQUZR0HZVI8NEFEIxGLTM3oL4DHkCSL0vSBOlhWvjbk16bQEGvvtw==,iv:jWPOlyIp+wYyS/aJ+wANkUVJCFA6gfcBllqX2NbfDNI=,tag:v+YEYl8F++XJkHQfeOvgYg==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0a2dHaEI2a2lYWDNaU2tI
            R1JGZzNmZW9hVDhSQXJtc1ZsVWFUeWoxMGkwCnp2R1RicVpsSVdnU3YzMFNzYytI
            MFZWNjNzSWxWdytCbStkSzhkUm5ib0EKLS0tIHZNZ09IVkNIczZ3WVJNMDFWd2ds
            cE1obmRQeEdtZGxLd1pIU0s5bmxGNFkKpGgA+tXgDpDkGNY9OlzYEDts+EItF5XM
            yPv4XB78SIuUFjcBw9k5vO7aKjZROgHkqK21Dgs7yO2ETGNMue0lsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T17:33:16Z"
    mac: ENC[AES256_GCM,data:uSuIllkv9M1x9wQZRtCQDQozpMX+XhKq9HdcC5R1o/QiqwVEmG5CPQcVwV7kHqc/r0RQ6v3KXSpVLAL8MwLXUWD8MrLTl9Jhi2seEyOH+ZFuc7DB/gtQKGE6byAyjparmvA5byEWSdV5wSKVFSafni8p4tDiT9b/1rdjh9X6ipU=,iv:VWJo1R7MMdzvWXTgr9qYRJbSwDUfyPsCemFUKiEZPJ0=,tag:Z/tBgSREI9DTLCObynmUXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
