kanidm_admin_password: ENC[AES256_GCM,data:j09LDOh9Zw1ksWZn4VRFuHIPR8nb6H0nKALeqPqejtCLd6j5zCfxpBUoBnBgPWk/,iv:OFsl/pOwGr5X2n0pYUtaNG8Eepi3LxqyXpalHerdEYw=,tag:sevXq6Dj4IXq5YXtPwGdQQ==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUtlV1pVb3owcTlSYUR0
            cmpvbzk0bW1LeVFTWmhkZzNHVU1BZXBIZnhRClgxclZXQXpnQTZEQ2FSalZVNVNS
            Q3l4REo2T1dmWDVod1V5Z1pDUmJOREUKLS0tIEpRdzYyakM1ZkVwV1J5R0Fvcmcy
            RGVwaXgzWk42RGRCS1dDUEQ5eDhkWDQKXk9em9yn47tElOflT1xNLo4w8K+oFK3+
            nJWjPtFwsB3Qj/uj8qrZ/WsjfIW1TW3ovJj2x3uarkGCE1t1w7hhfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T11:56:34Z"
    mac: ENC[AES256_GCM,data:aXb/M9Y565oR4OUi4eUnnCnEeKQ6fwEnc/hYv5t4WQKba1kQN5FmeKRPCEm0JeM5ldNnqXIF4A5iYE2yTuo/YAPIK3/lL/djxbK8BI7foir3Rkal/XgFviuqkSeAadokaKNkOnJcw+j+GqmSaLl9gmD56siWPum3eokoo84MyCU=,iv:MPD5qEzQwzoAAHzfVx4k7fiIwjmUMvsOYMiG0owIghE=,tag:jgZoSHGNH40bloKnNoBubQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
