kanidm_admin_password: ENC[AES256_GCM,data:ka+YQOUrfqE88g==,iv:DHGbdPiid4/jsz9dSIYX/S85BLJ3E9/WRYpKivwHRCk=,tag:P5sb8BqUDv/zir+tvTjP8w==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUtlV1pVb3owcTlSYUR0
            cmpvbzk0bW1LeVFTWmhkZzNHVU1BZXBIZnhRClgxclZXQXpnQTZEQ2FSalZVNVNS
            Q3l4REo2T1dmWDVod1V5Z1pDUmJOREUKLS0tIEpRdzYyakM1ZkVwV1J5R0Fvcmcy
            RGVwaXgzWk42RGRCS1dDUEQ5eDhkWDQKXk9em9yn47tElOflT1xNLo4w8K+oFK3+
            nJWjPtFwsB3Qj/uj8qrZ/WsjfIW1TW3ovJj2x3uarkGCE1t1w7hhfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T16:18:39Z"
    mac: ENC[AES256_GCM,data:y4neEZuGobt5O6UgacmSZoB6lxtNfM+GWyrmjmBJ2yoSuACpGyC62GhEvvJf8PGymnb8sQYo4VigFbVqURmwV01aNHCF937/52zh/JvQB1MagPel2RPyUC5r//RD1RuOh97bS7W87Gc/R3o76g9K1EYU0pqNv2VQNxXKnlPWWsc=,iv:HYQUwjhR6YSLVTD4WreJ/zYrwOC35hJVw2aEtzm6nrk=,tag:j2V82uioUDZFMAgz6smrxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
