kanidm_admin_password: ENC[AES256_GCM,data:OLx/AxZt4G1hDNbiH6fFrVeyghYhtYT0EtWY40wcgfmW/wxOC+MVzzKjeGYI3clQ,iv:FlbDxYYWwUbzAoJ48GzLrEVYKXydO3bzU359DDrZgKA=,tag:GqZEbLj2H14eXtxwdv9ibg==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUtlV1pVb3owcTlSYUR0
            cmpvbzk0bW1LeVFTWmhkZzNHVU1BZXBIZnhRClgxclZXQXpnQTZEQ2FSalZVNVNS
            Q3l4REo2T1dmWDVod1V5Z1pDUmJOREUKLS0tIEpRdzYyakM1ZkVwV1J5R0Fvcmcy
            RGVwaXgzWk42RGRCS1dDUEQ5eDhkWDQKXk9em9yn47tElOflT1xNLo4w8K+oFK3+
            nJWjPtFwsB3Qj/uj8qrZ/WsjfIW1TW3ovJj2x3uarkGCE1t1w7hhfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T18:03:01Z"
    mac: ENC[AES256_GCM,data:pcXX+K6pkM4JIbNu4w2lENujBSYe23wEtfRWPjBVStrSgo+96YodDwtOh8DEuk6mnIeynW/A0Qp/BAwoX+K8+X1ULjeTJn1lT2hX/N77CKXpMiEN+KYZLnNHBrUiiIkRrr9kUXpYwP0qsEfmFFuKMW5Y13dRZSM6EW1s7yrli9o=,iv:Xp6bKnJ/3HLapRDt4Ll5qOywwBgcDRZ4qWhfF2hR5/Q=,tag:raxqLwC5jo7ao1vHf8nCKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
