kanidim_admin_password: ENC[AES256_GCM,data:1mEix3hM12UG/Q==,iv:BAztU4JBlSd5Xt0sqfFa6iYNPUDiv37LnodHPj6NDfU=,tag:ruqVz0Cu8ZES4OtuwIbAHQ==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbUtlV1pVb3owcTlSYUR0
            cmpvbzk0bW1LeVFTWmhkZzNHVU1BZXBIZnhRClgxclZXQXpnQTZEQ2FSalZVNVNS
            Q3l4REo2T1dmWDVod1V5Z1pDUmJOREUKLS0tIEpRdzYyakM1ZkVwV1J5R0Fvcmcy
            RGVwaXgzWk42RGRCS1dDUEQ5eDhkWDQKXk9em9yn47tElOflT1xNLo4w8K+oFK3+
            nJWjPtFwsB3Qj/uj8qrZ/WsjfIW1TW3ovJj2x3uarkGCE1t1w7hhfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T15:10:17Z"
    mac: ENC[AES256_GCM,data:MA7i2KFX00nvdWkuzLSE9xY8il4j+3o3nyMpTh5aB22/EDgYzp58kx3xMH39TKBOoMl5Im0Dk0ydiRTMY/h7E6Hsgm2qlMHnEHyX/KD9kdGl300IOzJqQ+GvHEbB/2iPJUU/GpXCO01/IvMz0UXr0EASN7iNHfHaGcatPDJbZec=,iv:W64lLjcSowu0eLTBgjf7o0kz3w7GRzuy0RsPHfmb2fE=,tag:GcvLciW56/OLSKbDUM1EZg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
