admin_password: ENC[AES256_GCM,data:a9F+M1oYoLh2jw==,iv:8cdF7QYHP0+OlMVnpx92yL2rLMExi62I5M32HMDzAmM=,tag:+QGSPwPLGLYYRV40hIACkg==,type:str]
kanidm_link: ENC[AES256_GCM,data:UtS77xQRGofP1oUo8JYmLeKNXN5MqJZyc/meLEvyPPjCsgjzuscxaWAt4bqvy2Grtt+Y24Ldw/cgFcgtmX7ZYNT3DZfRFCGJ4exqaF9jf9U+fvhMz0nYsd+JMzrwwiVM7afNNfk/2b3eyYRGExAk2r/vWI9Qtl521qSKxtCrjgn6yaF4XeUmAcJJ/wtLDdu41TT+xlAD3Gi+f8rgfKQ5dxMc44YhD/yADvEW5KttptyaRqe5WdbvhyfvqZiAFaN1lzXU2g7IVhODENzWzGUR3suvuQRzqOq7gHEY4AsDIs58emNHvcMuT+mmIa36vDcPhRm1TL8c15mxJqQ1ljF5aYlrgd8J6B024Q04crLoijzENV3FWPl3meDrIPTKVUwcpnFVPSS0YVT7AJZRPNKBcd2R+pqHqmCoiCekpcJ9xc1Ju2gJ5zhZDRv7TfNvxXtPE3ra9nXhm4qe92hFYIlhh+6GtSDkGgCKs1JStK4WfhbXcdTIJjmzDF+RLWNvWriLBFysv9fC4J0qeXBT22Mn+1RGlQbfU2mvAz1oJh09,iv:5bG9+OeIKQhLNqgI4wHEGmTN2YvaAPq46n5+dnFOPm0=,tag:rPV49Eeu6XJNtilodsCZfw==,type:str]
stalwart_client_secret: ENC[AES256_GCM,data:vfORG7wH0/w2VLmFy+Sk6vgjxor9XWUjkAdxG8VXK7uKFT1bxIDDGA8gakw=,iv:6kAsJHDHU/pbo0CubHaXAfQD2owSCjGKZxW9OhLCWSA=,tag:QqPUEGBH1U5uVdxuDfwylQ==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T20:48:06Z"
    mac: ENC[AES256_GCM,data:Um7LeVymKuXqru+ovEiM0+Tt20BSZazURS4rgQ2hSpAlv7oG9LQ32hIbuo5Ugh4mWLELHKiPFrFbNalneiSjQBDAOSywBc8fNZfWXli6KzaeakJcFR63+Ds+scoWuK7z35iuHGj79JWzKdp67F/R4qUp4tbbNOZzfj4FEGMz2UU=,iv:+rDcKKCIIQnfSFF7a5e8oGGMFVIBXwkKBcA+ULzXhUs=,tag:PLjcrIiFKkitvnYjXzqUkQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
