admin_password: ENC[AES256_GCM,data:a9F+M1oYoLh2jw==,iv:8cdF7QYHP0+OlMVnpx92yL2rLMExi62I5M32HMDzAmM=,tag:+QGSPwPLGLYYRV40hIACkg==,type:str]
kanidm_link: ENC[AES256_GCM,data:szGnGoCcYdQJk10OyURojqWekus=,iv:bA7PUk/uBz2mRIZgGmNZbTw/trJOcYuCQw/nBM2g92E=,tag:4gOjz8KWLWlcg5PJV7PrwA==,type:str]
stalwart_client_secret: ENC[AES256_GCM,data:qAJDgddt2gXm4gnq2kDEtEqDc9Rl3Uc/Wcb9lEco9mbcmgERAet9WUOA93KYcqm9,iv:uvVM32c66SxHbGgB67eFQ5xcakqPz6W/PBJ05uLhD2I=,tag:HPyG38i6v//ho/K43H0VPg==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T06:38:57Z"
    mac: ENC[AES256_GCM,data:5vIPWLLtp9j0fRlMYjliepVdtYTDVYzSV4YypkB1tV3AwlGhy64+Nm/iD2fMIl9PptIWMKgV+7Fd1x3SLVzlGcwL0VFoxH9J0KQaB3Z1x901kMRxLzLgaNreaxn1/O6be1u1YvQmW8JWlworo3lO4se2Xu8qtBG/wvUFvXrImIY=,iv:6v5WreQwHPpdV7kfiQ7XdjQ4gx1ESUObYbOC1s4BYAM=,tag:+z0Nuqgt/UJB5bXzO4ck2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
