admin_password: ENC[AES256_GCM,data:a9F+M1oYoLh2jw==,iv:8cdF7QYHP0+OlMVnpx92yL2rLMExi62I5M32HMDzAmM=,tag:+QGSPwPLGLYYRV40hIACkg==,type:str]
kanidm_link: ENC[AES256_GCM,data:szGnGoCcYdQJk10OyURojqWekus=,iv:bA7PUk/uBz2mRIZgGmNZbTw/trJOcYuCQw/nBM2g92E=,tag:4gOjz8KWLWlcg5PJV7PrwA==,type:str]
oidc_secret: ENC[AES256_GCM,data:9ZO9+3zXpPYCzLgtTfUOL3uZXzM=,iv:747aZpL8HWbRg09ITFDpzAJnDN6OlpY894TQvo5d684=,tag:wHVFA8up/jDoVVqzptrJvg==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T15:21:06Z"
    mac: ENC[AES256_GCM,data:DfGGTYTyAUsxJSmZeFTby20l9+V4keWjxHvJVa23GFZxIjMxw8L7BhrKd0O4F2SyG7m7awBxENkuQTjKcABp72kdOFTKI3kTqYKo7qH5fAQ1pRQay6ACQ42UMeMBwI1OUcG/nH3bf4A7zn4yFQP/22w6oSbhtwrIuHmoFF4rUr8=,iv:3XtU4vAc1Xyf0ZjB7HhcxKCoKANI4v0ortHst3vKj1c=,tag:55wFyw/YusXmTV3SJinFOw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
