admin_password: ENC[AES256_GCM,data:a9F+M1oYoLh2jw==,iv:8cdF7QYHP0+OlMVnpx92yL2rLMExi62I5M32HMDzAmM=,tag:+QGSPwPLGLYYRV40hIACkg==,type:str]
kanidm_link: ENC[AES256_GCM,data:szGnGoCcYdQJk10OyURojqWekus=,iv:bA7PUk/uBz2mRIZgGmNZbTw/trJOcYuCQw/nBM2g92E=,tag:4gOjz8KWLWlcg5PJV7PrwA==,type:str]
sops:
    age:
        - recipient: age1cnkpqa4lqwav6c4hptj7f2x0ct5ms9qts2mpcqs756nrjqdxt5nsg5v6ng
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMEhRNnV2K0pyVUZDckxT
            alMyTzdFNGlNTUtMaklVM0l2b3puNjlwZ1JvCmdQU0o4eDE4WGErVStGTCtLSnFu
            cW0xUWVKUG5kMzdaZE96Qit4L3NzcHMKLS0tIHEvU0o5anBBNkVkdzVNN3JWNnZ5
            eVZVcEtwRWxCWXNnL09DSURWOFZjY1UKTW8ZGb2E1IAAFwWfWSKgyYgtWZwWAdNA
            zanUuBYNWG+9s5ZYr3Jo0BWT4CohuL99weJ2biHc/zHR+MVWwxz5GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T13:30:24Z"
    mac: ENC[AES256_GCM,data:+lz0hqBY8m8+byPPyDu1NoGazTpCN09ljRXzKOXkO5o+1C1w5Tg4NRJxLzmqIPsFMVrlOqQ44xVgBffkAjs7ga96wt7/+GjBzgUZ0X9MbDL8LVLUzdJmjMY1L3Cst43lfphwailZTDTsmE2qV36QF45a9Esz3xpuC7/WfTTf2AQ=,iv:YK4KnOgOOuRU7cCqkorP00DTi2nI4z01xXGqO+6rVgI=,tag:KoANWUo/ajNM6dYqqvLctA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
